# Generated by Django 4.0.5 on 2022-06-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=15)),
                ('studentclass', models.CharField(max_length=10)),
                ('studentbdate', models.DateField(verbose_name='birth date')),
                ('studentage', models.IntegerField(max_length=2)),
                ('studenthobby', models.CharField(max_length=10)),
                ('studentfavsub', models.CharField(max_length=10)),
            ],
        ),
    ]
